language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t 290803/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true 290803/react-test npm test

after_success:
  - docker build -t 290803/multi-client ./client
  - docker build -t 290803/multi-nginx ./nginx
  - docker build -t 290803/multi-server ./server
  - docker build -t 290803/multi-worker ./worker
  # login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push 290803/multi-client
  - docker push 290803/multi-nginx
  - docker push 290803/multi-server
  - docker push 290803/multi-worker
